// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTk-Apqq1PoEfdJ-XEvwgTXRQalkcRtXw',
    appId: '1:516813553794:web:2830bbdfaed9c54fdf349b',
    messagingSenderId: '516813553794',
    projectId: 'hackathonproject-67399',
    authDomain: 'hackathonproject-67399.firebaseapp.com',
    storageBucket: 'hackathonproject-67399.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCarpMtNsq28T33lT-OG1BOTtcy3M2DdEI',
    appId: '1:516813553794:android:0d4da584577192d1df349b',
    messagingSenderId: '516813553794',
    projectId: 'hackathonproject-67399',
    storageBucket: 'hackathonproject-67399.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrBpWpVIEbtCxZlBIJM_XsDv-EA_Te_pw',
    appId: '1:516813553794:ios:7954172edeeef371df349b',
    messagingSenderId: '516813553794',
    projectId: 'hackathonproject-67399',
    storageBucket: 'hackathonproject-67399.firebasestorage.app',
    iosBundleId: 'com.hackathonproject.hackathonproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrBpWpVIEbtCxZlBIJM_XsDv-EA_Te_pw',
    appId: '1:516813553794:ios:7954172edeeef371df349b',
    messagingSenderId: '516813553794',
    projectId: 'hackathonproject-67399',
    storageBucket: 'hackathonproject-67399.firebasestorage.app',
    iosBundleId: 'com.hackathonproject.hackathonproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTk-Apqq1PoEfdJ-XEvwgTXRQalkcRtXw',
    appId: '1:516813553794:web:b668689a513615d1df349b',
    messagingSenderId: '516813553794',
    projectId: 'hackathonproject-67399',
    authDomain: 'hackathonproject-67399.firebaseapp.com',
    storageBucket: 'hackathonproject-67399.firebasestorage.app',
  );
}
